### ISSUE TITLE
Problems with execution dmn-xlsx-cli-0.2.0.jar

### ISSUE THREAD

**Issue by monkeysmart** [camunda-community-hub/camunda-dmn-xlsx#26]
Hi!
I’m trying to use excel table to DMN table converter by executing command
`java -jar dmn-xlsx-cli-0.2.0.jar --inputs A --outputs B "C:\xlsdmn\test2.xlsx" "C:\xlsdmn\test2.dmn"`
But it throws an exception
`PS C:\xlsdmn> java -jar dmn-xlsx-cli-0.2.0.jar --inputs A --outputs B "C:\xlsdmn\test2.xlsx" "C:\xlsdmn\test2.dmn"
log4j:WARN No appenders could be found for logger (org.docx4j.jaxb.Context).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Could not convert file: Could not determine worksheet
java.lang.RuntimeException: Could not determine worksheet
        at org.camunda.bpm.dmn.xlsx.XlsxConverter.convert(XlsxConverter.java:65)
        at org.camunda.bpm.dmn.xlsx.cli.CommandLineConverter.main(CommandLineConverter.java:71)
Caused by: java.lang.NullPointerException
        at org.camunda.bpm.dmn.xlsx.XlsxConverter.convert(XlsxConverter.java:63)
        ... 1 more`
[excel document](http://bitrix.arsins.ru/test2.xlsx)
Does anybody know what’s the problem with this?

**Comment by kunalag** [comment]
Try using this - 
[dmn-xlsx-cli-0.2.1-SNAPSHOT.jar.zip](https://github.com/camunda/camunda-dmn-xlsx/files/4166388/dmn-xlsx-cli-0.2.1-SNAPSHOT.jar.zip)

I was downloading the xlsx file via google spreadsheets.
I was also getting the same error - During debugging, I found that the converter jar is failing when getting the properties, hence giving exception. By adding an extra check, worked like a charm.

https://github.com/camunda/camunda-dmn-xlsx/pull/28
